# Generated by Django 5.0.3 on 2024-03-21 14:18

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
