# Generated by Django 5.0.3 on 2024-04-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipe_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body_cz',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name_cz',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description_cz',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='title_cz',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='title_en',
        ),
    ]
