# Generated by Django 5.0.3 on 2024-04-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_remove_recipe_ingredients_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
    ]
