# Generated by Django 5.0.3 on 2024-04-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
