# Generated by Django 5.0.3 on 2024-04-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auser_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
