# Generated by Django 5.0.3 on 2024-04-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_auser_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AUser',
        ),
    ]
