# Generated by Django 5.0.3 on 2024-04-16 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
