# Generated by Django 5.0.3 on 2024-04-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='pfp',
        ),
    ]
