# Generated by Django 5.0.3 on 2024-04-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_profile_picture_userprofile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(blank=True, default='pfp/default.png', null=True, upload_to='pfp'),
        ),
    ]
