# Generated by Django 5.0.3 on 2024-04-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_userprofile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pfp',
            field=models.ImageField(blank=True, default='pfp/default.png', null=True, upload_to='pfp', verbose_name='pfp'),
        ),
    ]
