# Generated by Django 5.0.4 on 2024-04-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_alter_recipe_description_alter_recipe_ingredients_and_more'),
        ('users', '0017_alter_userprofile_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_recipes',
            field=models.ManyToManyField(to='recipes.recipe'),
        ),
    ]
